name: 'Install Rust'
description: 'Install Rust'
inputs:
  rust-version:
    description: 'Which version of Rust to install'
    required: true
  cargo-lambda-version:
    description: 'Which version of cargo-lambda to install'
    required: true
  zig-version:
    description: 'Which version of Zig compiler to install'
    required: true
runs:
  using: "composite"
  steps:
    - run: rustup override set ${{ inputs.rust-version }}
      shell: bash 
    - run: rustup toolchain install stable
      shell: bash 
    - run: rustup target install x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu
      shell: bash 