name: 'Build Lambdas'
on:
  push:
    branches:
      - main
jobs:
  test:
    - id: Install Rust
      uses: .github/actions/install-rust
      with:
        rust-version: '1.71.0'
        zig-version: '0.10.1'
        cargo-lambda-version: '0.19.2'